LATEX=pdflatex
LATEXMK=latexmk
LATEXOPT=-file-line-error


MAIN=report
SOURCES=$(MAIN).tex Makefile 
# FIGURES := $(shell ls fig/*.pdf)

all:    $(MAIN).pdf

.refresh:
	touch .refresh

$(MAIN).pdf: $(MAIN).tex .refresh $(SOURCES) # $(FIGURES)
	$(LATEXMK) -jobname=build/report -pdf $(MAIN).tex

force:
	touch .refresh
	$(MAKE) $(MAIN).pdf

.PHONY: clean force all

clean:
	$(LATEXMK) -C $(MAIN).tex
	rm -f $(MAIN).pdfsync
	rm -rf *~ *.tmp
